services:
  merch-store-service:
    build: .
    container_name: merch-store-service
    ports:
      - '8080:8080'
    environment:
      # Ваши переменные окружения
      - PORT=8080
      - DATABASE_URL=postgres://postgres:password@db:5432/merch_store?sslmode=disable
      - JWT_SECRET=JASd;j10sbdjks3bld4je';bvp7bbc,mneq=clj_eh-cvph3;vvc2o187t321hvj
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: merch_store
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d merch_store']
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

networks:
  internal:
